version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Point client to same-origin API in container
        - REACT_APP_API_BASE_URL=/api/v1
    env_file:
      - ./server/.env
    environment:
      # Force server to listen on container port 5000 (exposed above)
      - PORT=5000
    ports:
      # Expose container port 5000 as 5001 on host (to avoid macOS Control Center on 5000)
      - "5001:5000"
    restart: unless-stopped
    depends_on: []

  # Optional: Uncomment and use a mongo service if you want a local mongo for development
  # mongo:
  #   image: mongo:6
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongo-data:/data/db

# volumes:
#   mongo-data:
