version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Point client to same-origin API in container
        - REACT_APP_API_BASE_URL=/api/v1
    ports:
      # Expose NGINX port 80 as 5001 on host (avoid macOS Control Center conflicts)
      - "5001:80"
    restart: unless-stopped
    depends_on: []

  # Optional: Uncomment and use a mongo service if you want a local mongo for development
  # mongo:
  #   image: mongo:6
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongo-data:/data/db

# volumes:
#   mongo-data:
