version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    env_file:
      - ./server/.env
    ports:
      - "3005:3005"
    restart: unless-stopped
    working_dir: /usr/src/app
    volumes:
      - ./server:/usr/src/app:ro
    depends_on: []

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_BASE_URL=${REACT_APP_API_BASE_URL}
    env_file:
      - ./.env
    ports:
      - "3000:80"
    restart: unless-stopped
    depends_on:
      - backend

# Optional: Uncomment and use a mongo service if you want a local mongo for development
#  mongo:
#    image: mongo:6
#    ports:
#      - "27017:27017"
#    volumes:
#      - mongo-data:/data/db

#volumes:
#  mongo-data:
